# coding: utf-8

"""
    LSP Contracts

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lsp_api_contracts.models.cmd import Cmd

class TestCmd(unittest.TestCase):
    """Cmd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Cmd:
        """Test Cmd
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Cmd`
        """
        model = Cmd()
        if include_optional:
            return Cmd(
                type_name = ''
            )
        else:
            return Cmd(
                type_name = '',
        )
        """

    def testCmd(self):
        """Test Cmd"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
