# coding: utf-8

"""
    LSP Contracts

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lsp_api_contracts.models.lsp_request_cmd import LspRequestCmd

class TestLspRequestCmd(unittest.TestCase):
    """LspRequestCmd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LspRequestCmd:
        """Test LspRequestCmd
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LspRequestCmd`
        """
        model = LspRequestCmd()
        if include_optional:
            return LspRequestCmd(
                type_name = 'CmdNativeAppDelete',
                open_input_1 = '',
                open_input_2 = '',
                delete_input_1 = ''
            )
        else:
            return LspRequestCmd(
                type_name = 'CmdNativeAppDelete',
        )
        """

    def testLspRequestCmd(self):
        """Test LspRequestCmd"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
