# coding: utf-8

"""
    LSP Contracts

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lsp_api_contracts.models.lsp_request import LspRequest

class TestLspRequest(unittest.TestCase):
    """LspRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LspRequest:
        """Test LspRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LspRequest`
        """
        model = LspRequest()
        if include_optional:
            return LspRequest(
                context = lsp_api_contracts.models.context.Context(
                    connection = lsp_api_contracts.models.connection.Connection(
                        account = '', 
                        user = '', ), 
                    env = {
                        'key' : ''
                        }, 
                    project_path = '', ),
                cmd = lsp_api_contracts.models.cmd.Cmd(
                    type_name = '', )
            )
        else:
            return LspRequest(
                context = lsp_api_contracts.models.context.Context(
                    connection = lsp_api_contracts.models.connection.Connection(
                        account = '', 
                        user = '', ), 
                    env = {
                        'key' : ''
                        }, 
                    project_path = '', ),
                cmd = lsp_api_contracts.models.cmd.Cmd(
                    type_name = '', ),
        )
        """

    def testLspRequest(self):
        """Test LspRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
