name: 'dbt_integration_project'
version: '1.0.0'

profile: 'dbt_integration_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_integration_project:
    example:
      +materialized: view
