version: 2

models:
  - name: first_model_with_local
    description: "First model using local package macros"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name field"
      - name: uppercase_name
        description: "Uppercased name using local uppercase macro"
  
  - name: second_model_with_local
    description: "Second model using local package macros"
    columns:
      - name: id
        description: "Primary key"
      - name: name
        description: "Name field"
      - name: uppercase_name
        description: "Uppercased name"
