services:
  package-builder:
    build: .
    volumes:
      - ../../:/snowflake-cli
  cli-builder:
    build: .
    volumes:
      - ../../:/snowflake-cli
    environment:
      - RELEASE_TYPE
    command: /bin/bash -c "pyenv exec hatch build --clean"
  cli-test:
    build: .
    volumes:
      - ../../:/snowflake-cli
    environment:
      - RELEASE_TYPE
    command: /bin/bash -c "eval \"$(pyenv init -)\" && ./scripts/packaging/python/test_cli_whl.sh"
  cli-labs-builder:
    build: .
    volumes:
      - ../../:/snowflake-cli
    environment:
      - RELEASE_TYPE
    command: /bin/bash -c "pyenv exec hatch run legacy-pypi-build"
  cli-labs-test:
    build: .
    volumes:
      - ../../:/snowflake-cli
    environment:
      - RELEASE_TYPE
    command: /bin/bash -c "eval \"$(pyenv init -)\" && ./scripts/packaging/python/test_cli_labs_whl.sh"
