# Copyright (c) 2024 Snowflake Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Conservative build config with disabled modern CPU features for native x86_64 builds
# Apply these flags globally when building on x86_64 systems
[build]
rustflags = [
    "-C", "debuginfo=2",
    "-C", "target-feature=-avx",
    "-C", "target-feature=-avx2",
    "-C", "target-feature=-avx512f",
    "-C", "target-feature=-avx512cd",
    "-C", "target-feature=-avx512dq",
    "-C", "target-feature=-avx512bw",
    "-C", "target-feature=-avx512vl",
    "-C", "target-feature=-avx512ifma",
    "-C", "target-feature=-avx512vbmi",
    "-C", "target-feature=-avx512vbmi2",
    "-C", "target-feature=-avx512vnni",
    "-C", "target-feature=-avx512bitalg",
    "-C", "target-feature=-avx512vpopcntdq",
    "-C", "target-feature=-fma",
    "-C", "target-feature=-bmi1",
    "-C", "target-feature=-bmi2",
    "-C", "target-feature=-lzcnt",
    "-C", "target-feature=-pclmulqdq",
    "-C", "target-feature=-movbe"
]

# Environment variables for C/C++ compilation
[env]
CFLAGS = "-mno-avx -mno-avx2 -mno-avx512f -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx512vbmi2 -mno-avx512vnni -mno-avx512bitalg -mno-avx512vpopcntdq -mno-fma -mno-bmi -mno-bmi2 -mno-lzcnt -mno-pclmul -mno-movbe -O2"
CXXFLAGS = "-mno-avx -mno-avx2 -mno-avx512f -mno-avx512cd -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx512vbmi2 -mno-avx512vnni -mno-avx512bitalg -mno-avx512vpopcntdq -mno-fma -mno-bmi -mno-bmi2 -mno-lzcnt -mno-pclmul -mno-movbe -O2"

# Static linking configuration for fully self-contained binaries
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-static",
    # Conservative CPU features (same as global but for static builds)
    "-C", "target-feature=-avx",
    "-C", "target-feature=-avx2",
    "-C", "target-feature=-avx512f",
    "-C", "target-feature=-avx512cd",
    "-C", "target-feature=-avx512dq",
    "-C", "target-feature=-avx512bw",
    "-C", "target-feature=-avx512vl",
    "-C", "target-feature=-avx512ifma",
    "-C", "target-feature=-avx512vbmi",
    "-C", "target-feature=-avx512vbmi2",
    "-C", "target-feature=-avx512vnni",
    "-C", "target-feature=-avx512bitalg",
    "-C", "target-feature=-avx512vpopcntdq",
    "-C", "target-feature=-fma",
    "-C", "target-feature=-bmi1",
    "-C", "target-feature=-bmi2",
    "-C", "target-feature=-lzcnt",
    "-C", "target-feature=-pclmulqdq",
    "-C", "target-feature=-movbe"
]

[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-static",
    # Conservative CPU features (same as global but for static builds)
    "-C", "target-feature=-avx",
    "-C", "target-feature=-avx2",
    "-C", "target-feature=-avx512f",
    "-C", "target-feature=-avx512cd",
    "-C", "target-feature=-avx512dq",
    "-C", "target-feature=-avx512bw",
    "-C", "target-feature=-avx512vl",
    "-C", "target-feature=-avx512ifma",
    "-C", "target-feature=-avx512vbmi",
    "-C", "target-feature=-avx512vbmi2",
    "-C", "target-feature=-avx512vnni",
    "-C", "target-feature=-avx512bitalg",
    "-C", "target-feature=-avx512vpopcntdq",
    "-C", "target-feature=-fma",
    "-C", "target-feature=-bmi1",
    "-C", "target-feature=-bmi2",
    "-C", "target-feature=-lzcnt",
    "-C", "target-feature=-pclmulqdq",
    "-C", "target-feature=-movbe"
]
