/**
 * LSP Contracts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CmdNativeAppDelete {
    'typeName': CmdNativeAppDelete.TypeNameEnum;
    'deleteInput1'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "typeName",
            "baseName": "type_name",
            "type": "CmdNativeAppDelete.TypeNameEnum"
        },
        {
            "name": "deleteInput1",
            "baseName": "delete_input_1",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CmdNativeAppDelete.attributeTypeMap;
    }
}

export namespace CmdNativeAppDelete {
    export enum TypeNameEnum {
        CmdNativeAppDelete = <any> 'CmdNativeAppDelete'
    }
}
