/**
 * LSP Contracts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CmdPocInput {
    'input1'?: string;
    'input2'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "input1",
            "baseName": "input_1",
            "type": "string"
        },
        {
            "name": "input2",
            "baseName": "input_2",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CmdPocInput.attributeTypeMap;
    }
}

