/**
 * LSP Contracts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Context } from './context';
import { LspRequestCmd } from './lspRequestCmd';

export class LspRequest {
    'context': Context;
    'cmd': LspRequestCmd;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "context",
            "baseName": "context",
            "type": "Context"
        },
        {
            "name": "cmd",
            "baseName": "cmd",
            "type": "LspRequestCmd"
        }    ];

    static getAttributeTypeMap() {
        return LspRequest.attributeTypeMap;
    }
}

