/**
 * LSP Contracts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CmdNativeAppDelete } from './cmdNativeAppDelete';
import { CmdNativeAppOpen } from './cmdNativeAppOpen';

export class LspRequestCmd {
    'typeName': LspRequestCmd.TypeNameEnum;
    'openInput1'?: string;
    'openInput2'?: string;
    'deleteInput1'?: string;

    static discriminator: string | undefined = "typeName";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "typeName",
            "baseName": "type_name",
            "type": "LspRequestCmd.TypeNameEnum"
        },
        {
            "name": "openInput1",
            "baseName": "open_input_1",
            "type": "string"
        },
        {
            "name": "openInput2",
            "baseName": "open_input_2",
            "type": "string"
        },
        {
            "name": "deleteInput1",
            "baseName": "delete_input_1",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LspRequestCmd.attributeTypeMap;
    }
}

export namespace LspRequestCmd {
    export enum TypeNameEnum {
        CmdNativeAppDelete = <any> 'CmdNativeAppDelete'
    }
}
