name: Integration testing

on:
  pull_request:
    branches:
      - "**"
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main
      - features/*
  repository_dispatch:
    types: [ok-to-test-command]
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  define-matrix:
    uses: ./.github/workflows/matrix.yaml

  # Branch-based pull request
  integration-trusted:
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.define-matrix.outputs.os) }}
        python-version: ${{ fromJSON(needs.define-matrix.outputs.python) }}
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    uses: ./.github/workflows/test_trusted.yaml
    with:
      runs-on: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      python-env: integration
      hatch-run: integration:test
    secrets: inherit

  # Repo owner has commented /ok-to-test on a (fork-based) pull request
  integration-fork:
    needs: define-matrix
    strategy:
      fail-fast: true
      matrix:
        os: ${{ fromJSON(needs.define-matrix.outputs.os) }}
        python-version: ${{ fromJSON(needs.define-matrix.outputs.python) }}
    permissions:
      pull-requests: write
      checks: write
    if: |
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.slash_command.args.named.sha != '' &&
      contains(
        github.event.client_payload.pull_request.head.sha,
        github.event.client_payload.slash_command.args.named.sha
      )
    uses: ./.github/workflows/test_fork.yaml
    with:
      runs-on: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      python-env: integration
      hatch-run: integration:test
      job-name: integration-fork
    secrets: inherit
